#!/bin/sh
#
# ISCO utility: Copy root FS image to a partition
#
# cprootimg [imageFile] [partition]
# - imageFile: root filesystem image file
#   By default, will use the file images/rootfs.ext3 from
#   the boot partition.  
#
# - partition: optional partition name. 
#   By default, copies to designated root FS partition 
#   where root isn't currently mounted.
#

# Partitions for SABRE Board
# eMMC contains active U-Boot
# Root FS in partition 2 on eMMC and SD card

# SABRE
#BOOTPART=mmcblk1p1
#BOOTMOUNT=/media/$BOOTPART
#ROOTPARTA=mmcblk0p2
#ROOTPARTB=mmcblk1p2
#DATAPART=mmcblk0p3

# Beaglebone
# Issue: can't mount FAT with current kernel!!!
BOOTPART=mmcblk1p0
BOOTMOUNT=/media/$BOOTPART
ROOTPARTA=mmcblk0p2
ROOTPARTB=mmcblk0p4
DATAPART=mmcblk0p3

FTYPE=tar.bz2
#FTYPE=ext3

# IMGSAVEDIR can't be in ROOTPARTA or ROOTPARTB
IMGSAVEDIR=/home/root/images
#IMGSAVEDIR=$BOOTMOUNT/images
IMGNAME=rootfs.$FTYPE
IMGFILE=$IMGSAVEDIR/$IMGNAME

if [ -n "$1" ]; then
    IMGFILE=$1
fi

if [ -n "$2" ]; then
    MMCDEV=/dev/"$2"
else
    # Muse use 'rdev' to get root because /proc/cmdline will show
    # ramdisk mount.
    ## Get currently mounted root partition from kernel command line
    #IS_PARTA_ROOT=`grep -c $ROOTPARTA /proc/cmdline`
    #IS_PARTB_ROOT=`grep -c $ROOTPARTB /proc/cmdline`
    IS_PARTA_ROOT=`/usr/sbin/rdev -r | grep -c $ROOTPARTA`
    IS_PARTB_ROOT=`/usr/sbin/rdev -r | grep -c $ROOTPARTB`

    if [ $IS_PARTA_ROOT -eq 1 ]; then
       MMCDEV=/dev/$ROOTPARTB
    elif [ $IS_PARTB_ROOT -eq 1 ]; then
       MMCDEV=/dev/$ROOTPARTA 
    else
       echo "Error: Did not find valid mount partition"
       exit 1
    fi
fi

# Copy image into the flash partition
echo "Updating $MMCDEV with $IMGFILE ..."

umount $MMCDEV 2>/dev/null

if [ "$FTYPE" == "ext3" ]; then
    dd if=$IMGFILE of=$MMCDEV bs=1024 || exit 1
else # bz2
    mkdir -p /media/newroot
    umount /media/newroot 2>/dev/null
    mount -t ext4 $MMCDEV /media/newroot
    rm -rf /media/newroot/*
    tar -xf $IMGFILE -m -C /media/newroot

# Beaglebone: copy DTB files
    cp $IMGSAVEDIR/*.dtb /media/newroot/boot

fi

echo "Image update Success!"

# Set file for initramfs to select the partition
echo "$MMCDEV" >$IMGSAVEDIR/rootfsdev

echo " "
echo " If U-Boot can't save env vars (bug), need to load ramdisk manually from there: "
echo " "
echo "  run loadramdisk; run ramboot"
echo " "

