#!/bin/sh
#
# Utility: Copy root FS image to a partition
#
# cprootimg [filetype][imageFile] [partition]
# - filetype: bz2 for bz2 image; otherwise ext3/4
# - imageFile: root filesystem image file
#   By default, will use the file images/rootfs.ext3 from
#   the boot partition.  
#
# - partition: optional partition name. 
#   By default, copies to designated root FS partition 
#   where root isn't currently mounted.
#

# Partitions for SABRE Board
# eMMC is mmcblk0 if no SD card inserted.
BOOTPART=mmcblk1p0
BOOTMOUNT=/media/$BOOTPART
ROOTPARTA=mmcblk0p2
ROOTPARTB=mmcblk0p3
DATAPART=mmcblk0p4

FTYPE=ext3
if [ "$1" == "bz2" ]; then
    FTYPE=tar.bz2
fi    

# IMGSAVEDIR can't be in ROOTPARTA or ROOTPARTB
IMGSAVEDIR=/home/root/images
#IMGSAVEDIR=$BOOTMOUNT/images
IMGNAME=rootfs.$FTYPE
IMGFILE=$IMGSAVEDIR/$IMGNAME

if [ -n "$2" ]; then
    IMGFILE=$2
fi

if [ -n "$3" ]; then
    MMCDEV=/dev/"$3"
else
    # Save image in partition that isn't currently the root device
    IS_PARTA_ROOT=`/usr/sbin/rdev -r | grep -c $ROOTPARTA`
    IS_PARTB_ROOT=`/usr/sbin/rdev -r | grep -c $ROOTPARTB`

    if [ $IS_PARTA_ROOT -eq 1 ]; then
       MMCDEV=/dev/$ROOTPARTB
    elif [ $IS_PARTB_ROOT -eq 1 ]; then
       MMCDEV=/dev/$ROOTPARTA 
    else
       echo "Error: Did not find valid mount partition"
       exit 1
    fi
fi

# Copy image into the flash partition
echo "Updating $MMCDEV with $IMGFILE ..."

umount $MMCDEV 2>/dev/null

if [ "$FTYPE" == "ext3" ]; then
    dd if=$IMGFILE of=$MMCDEV bs=1M
    
    if [ $? -ne 0 ]; then 
        echo "Filesystem copy failed!"
        exit 1
    fi 
else 
    # extract bz2 to existing FS, for development only
    mkdir -p /media/newroot
    umount /media/newroot 2>/dev/null
    mount -t ext4 $MMCDEV /media/newroot || exit 1
    rm -rf /media/newroot/*
    tar -xf $IMGFILE -m -C /media/newroot

# Beaglebone: copy DTB files
    cp $IMGSAVEDIR/*.dtb /media/newroot/boot

fi

echo "Image update Success!"

# Set file for initramfs to select the partition
echo "$MMCDEV" >$IMGSAVEDIR/rootfsdev

