#!/bin/sh
# ISCO: Make eMMC #2 partitions for Clarus board
#
# Logs:   6.0G ext4
# Unused: ~2.0G (unformatted)
if [ $# -eq 0 ]; then
    echo "Usage: $0 <device_node>"
    exit 1
fi

node=$1

# Stop udev from automatic mount
echo "/dev/mmc*" >>/etc/udev/mount.blacklist

umount ${node}p1 2>/dev/null
umount ${node}p2 2>/dev/null
umount ${node}p3 2>/dev/null
umount ${node}p4 2>/dev/null

# Destroy the partition table
dd if=/dev/zero of=${node} bs=1024 count=1
if [ $? -ne 0 ]; then echo "Disk partition clear failed!"; exit 1; fi

# call sfdisk to create partition table
sfdisk --force -uM ${node} << EOF
0,6144,83
EOF

if [ $? -ne 0 ]; then echo "Disk partitioning failed!"; exit 1; fi

umount ${node}p1 2>/dev/null
umount ${node}p2 2>/dev/null
umount ${node}p3 2>/dev/null
umount ${node}p4 2>/dev/null

mkfs.ext4 ${node}p1
if [ $? -ne 0 ]; then echo "Log FS make failed!"; exit 1; fi

echo "SUCCESS"
